
const rentalCars = [
  {
    name: "Suzuki Alto",
    image: "https://suzukipakistan.com/media/products/Automobiles/Alto/Colors/Studio-Session-524_04.jpg",
    pricePerDay: 2000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Toyota Corolla",
    image: "https://imgcdn.zigwheels.pk/large/gallery/exterior/14/118/toyota-corolla-front-angle-low-view.jpg",
    pricePerDay: 5000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Honda City",
    image: "https://tyrepoint.pk/wp-content/uploads/2018/10/Honda-City-tyrepoint.pk-1-wpv_325x325.jpg",
    pricePerDay: 4500,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Suzuki Cultus",
    image: "https://cache4.pakwheels.com/system/car_generation_pictures/6014/original/Suzuki_Cultus_-_PNG.png?1635945515",
    pricePerDay: 3000,
    location: "Rawalpindi, Pakistan",
  },
  {
    name: "Toyota Yaris",
    image: "https://files.toyota.com.bh/s3fs-public/2022-09/super-white.png?VersionId=BK7OGKWBSqXZ5o5V_5iox5dXFKZd0mwe",
    pricePerDay: 6000,
    location: "Faisalabad, Pakistan",
  },
  {
    name: "Honda Civic",
    image: "https://tyrepoint.pk/wp-content/uploads/2018/10/Honda-City-tyrepoint.pk-1-wpv_325x325.jpg",
    pricePerDay: 5000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Honda Civic",
    image: "https://tyrepoint.pk/wp-content/uploads/2018/10/Honda-City-tyrepoint.pk-1-wpv_325x325.jpg",
    pricePerDay: 5000,
    location: "Rawalpindi, Pakistan",
  },
  {
    name: "Suzuki Wagon R",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/4743/original/Suzuki_wagon_R_JDM.jpg?1515149131",
    pricePerDay: 2800,
    location: "Lahore, Pakistan",
  },
  {
    name: "Toyota Fortuner",
    image: "https://toyotacreek.com/wp-content/uploads/2019/12/Fortuner-Featured-Image-750x420.jpg",
    pricePerDay: 15000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Kia Sportage",
    image: "https://cache4.pakwheels.com/system/car_generation_pictures/7734/original/Sportage_white.jpeg?1720510978",
    pricePerDay: 10000,
    location: "Peshawar, Pakistan",
  },
  {
    name: "Kia Sportage",
    image: "https://cache4.pakwheels.com/system/car_generation_pictures/7734/original/Sportage_white.jpeg?1720510978",
    pricePerDay: 10000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Hyundai Tucson",
    image: "https://cache3.pakwheels.com/system/car_generation_pictures/6022/original/Tucson_-_PNG.png?1635948541",
    pricePerDay: 12000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Changan Alsvin",
    image: "https://changan.com.pk/upload/alsvin-feature-slider-exterior-02260222021851-drive.jpg",
    pricePerDay: 9000,
    location: "Quetta, Pakistan",
  },
  {
    name: "Proton Saga",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/6434/original/Proton_Saga_Front.jpg?1652337056",
    pricePerDay: 5000,
    location: "Multan, Pakistan",
  },
  {
    name: "DFSK Glory 580",
    image: "https://cache4.pakwheels.com/system/car_generation_pictures/6431/original/Glory_580_Pro_Front.jpg?1652179255",
    pricePerDay: 7500,
    location: "Karachi, Pakistan",
  },
  {
    name: "DFSK Glory 580",
    image: "https://cache4.pakwheels.com/system/car_generation_pictures/6431/original/Glory_580_Pro_Front.jpg?1652179255",
    pricePerDay: 7500,
    location: "Lahore, Pakistan",
  },
  {
    name: "Toyota Revo",
    image: "https://toyota-indus.com/wp-content/uploads/2022/10/Revo_Rocco_Grey-Graphite.png",
    pricePerDay: 18000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Toyota Revo",
    image: "https://toyota-indus.com/wp-content/uploads/2022/10/Revo_Rocco_Grey-Graphite.png",
    pricePerDay: 18000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Toyota Revo",
    image: "https://toyota-indus.com/wp-content/uploads/2022/10/Revo_Rocco_Grey-Graphite.png",
    pricePerDay: 18000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Suzuki Bolan",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/6421/original/Suzuki-Bolan-Front.jpg?1651125085",
    pricePerDay: 2000,
    location: "Faisalabad, Pakistan",
  },
  {
    name: "Suzuki Bolan",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/6421/original/Suzuki-Bolan-Front.jpg?1651125085",
    pricePerDay: 2000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Suzuki Bolan",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/6421/original/Suzuki-Bolan-Front.jpg?1651125085",
    pricePerDay: 2000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Suzuki Bolan",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/6421/original/Suzuki-Bolan-Front.jpg?1651125085",
    pricePerDay: 2000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Honda BR-V",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/6430/original/Honda_BRV_Front.jpg?1652159445",
    pricePerDay: 7000,
    location: "Rawalpindi, Pakistan",
  },
  {
    name: "Suzuki Swift",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/7441/original/SWIFT.jpg?1677750438",
    pricePerDay: 5000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Suzuki Swift",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/7441/original/SWIFT.jpg?1677750438",
    pricePerDay: 5000,
    location: "Rawalpindi, Pakistan",
  },
  {
    name: "Suzuki Swift",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/7441/original/SWIFT.jpg?1677750438",
    pricePerDay: 5000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Suzuki Swift",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/7441/original/SWIFT.jpg?1677750438",
    pricePerDay: 5000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Suzuki Swift",
    image: "https://cache1.pakwheels.com/system/car_generation_pictures/7441/original/SWIFT.jpg?1677750438",
    pricePerDay: 5000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Kia Picanto",
    image: "https://cache3.pakwheels.com/system/car_generation_pictures/6017/original/Picanto_-_PNG.png?1635946684",
    pricePerDay: 4000,
    location: "Peshawar, Pakistan",
  },
  {
    name: "Kia Picanto",
    image: "https://cache3.pakwheels.com/system/car_generation_pictures/6017/original/Picanto_-_PNG.png?1635946684",
    pricePerDay: 4000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Kia Picanto",
    image: "https://cache3.pakwheels.com/system/car_generation_pictures/6017/original/Picanto_-_PNG.png?1635946684",
    pricePerDay: 4000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Kia Picanto",
    image: "https://cache3.pakwheels.com/system/car_generation_pictures/6017/original/Picanto_-_PNG.png?1635946684",
    pricePerDay: 4000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Toyota Land Cruiser",
    image: "https://global.toyota/pages/news/images/2021/08/02/1330/001.jpg",
    pricePerDay: 20000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Toyota Land Cruiser",
    image: "https://global.toyota/pages/news/images/2021/08/02/1330/001.jpg",
    pricePerDay: 20000,
    location: "Karachi, Pakistan",
  },
  {
    name: "Hyundai Elantra",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/5381/original/elantra.jpg?1608016094",
    pricePerDay: 11000,
    location: "Lahore, Pakistan",
  },
  {
    name: "Hyundai Elantra",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/5381/original/elantra.jpg?1608016094",
    pricePerDay: 11000,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Hyundai Elantra",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/5381/original/elantra.jpg?1608016094",
    pricePerDay: 11000,
    location: "Karachi, Pakistan",
  },

  {
    name: "Suzuki Ciaz",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/4439/original/Suzuki_Ciaz_2017_%285%29.jpg?1486634979",
    pricePerDay: 5500,
    location: "Islamabad, Pakistan",
  },
  {
    name: "Suzuki Ciaz",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/4439/original/Suzuki_Ciaz_2017_%285%29.jpg?1486634979",
    pricePerDay: 5500,
    location: "Lahore, Pakistan",
  },
  {
    name: "Suzuki Ciaz",
    image: "https://cache2.pakwheels.com/system/car_generation_pictures/4439/original/Suzuki_Ciaz_2017_%285%29.jpg?1486634979",
    pricePerDay: 5500,
    location: "Karachi, Pakistan",
  }
];

export default rentalCars;
